### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'str' if -t option with negative value used

### ISSUE THREAD

**Issue by BeFiveINFO** [danrossi/loudness-cli#2]
I get a TypeError error by using -t option. Running the script with Python 2.7.15 on MacOS 10.13.5 (17F77)

I had to wrap args.target with float() to make it run.

Before

```
statsDict["gain"] = linearGain(statsDict["I"], args.targe));
```

After 

```
statsDict["gain"] = linearGain(statsDict["I"], float(args.target));
```

**Comment by danrossi** [comment]
I don't know how it was working I guess using defaults. The pr is in thanks.
